import { UserData } from './interfaces/user-data';

export const USERS: UserData[] = [
  {
    id: 3895,
    name: 'Tara Desai',
    email: 'tara_desai@jones-auer.io',
    gender: 'female',
    status: 'inactive',
  },
  {
    id: 3894,
    name: 'Msgr. Goswami Marar',
    email: 'goswami_msgr_marar@wiegand-mcclure.info',
    gender: 'male',
    status: 'inactive',
  },
  {
    id: 3893,
    name: 'Sarvin Sethi',
    email: 'sethi_sarvin@hettinger.co',
    gender: 'female',
    status: 'active',
  },
  {
    id: 3875,
    name: 'Digambara Dubashi',
    email: 'digambara_dubashi@littel-windler.org',
    gender: 'male',
    status: 'inactive',
  },
  {
    id: 3874,
    name: 'Shwet Prajapat',
    email: 'prajapat_shwet@daniel.biz',
    gender: 'female',
    status: 'active',
  },
  {
    id: 3873,
    name: 'Akshita Bharadwaj JD',
    email: 'bharadwaj_akshita_jd@daugherty.net',
    gender: 'male',
    status: 'active',
  },
  {
    id: 3872,
    name: 'Abhirath Reddy',
    email: 'abhirath_reddy@weissnat.name',
    gender: 'female',
    status: 'active',
  },
  {
    id: 3871,
    name: 'Menka Bhattacharya',
    email: 'bhattacharya_menka@mckenzie.biz',
    gender: 'male',
    status: 'active',
  },
  {
    id: 3870,
    name: 'Rukhmani Namboothiri',
    email: 'namboothiri_rukhmani@lueilwitz.net',
    gender: 'male',
    status: 'active',
  },
  {
    id: 3869,
    name: 'Nagabhushanam Verma',
    email: 'nagabhushanam_verma@abbott-cruickshank.org',
    gender: 'female',
    status: 'inactive',
  },
  {
    id: 3868,
    name: 'Dhatri Kaur Esq.',
    email: 'esq_dhatri_kaur@weber.com',
    gender: 'female',
    status: 'active',
  },
  {
    id: 3867,
    name: 'Nikita Chattopadhyay',
    email: 'chattopadhyay_nikita@terry.com',
    gender: 'female',
    status: 'inactive',
  },
  {
    id: 3866,
    name: 'Brahmdev Ganaka',
    email: 'brahmdev_ganaka@mayer.org',
    gender: 'female',
    status: 'active',
  },
  {
    id: 3865,
    name: 'Chandran Gupta',
    email: 'chandran_gupta@kozey-dach.biz',
    gender: 'male',
    status: 'active',
  },
  {
    id: 3864,
    name: 'Shankar Dutta Ret.',
    email: 'ret_shankar_dutta@zieme.org',
    gender: 'female',
    status: 'active',
  },
  {
    id: 3862,
    name: 'Suma Embranthiri',
    email: 'embranthiri_suma@kessler.co',
    gender: 'female',
    status: 'inactive',
  },
  {
    id: 3861,
    name: 'Shubhaprada Adiga',
    email: 'shubhaprada_adiga@murphy-jones.co',
    gender: 'female',
    status: 'active',
  },
  {
    id: 3860,
    name: 'Mangala Namboothiri',
    email: 'namboothiri_mangala@wyman-ward.org',
    gender: 'female',
    status: 'active',
  },
  {
    id: 3859,
    name: 'Lalita Devar',
    email: 'lalita_devar@blanda.org',
    gender: 'male',
    status: 'inactive',
  },
  {
    id: 3858,
    name: 'Dipesh Kaniyar',
    email: 'kaniyar_dipesh@mclaughlin.net',
    gender: 'male',
    status: 'active',
  },
];
